version: '3'
services:
  api:
    container_name: {{serverName}}
    image: $ApiImageTag 
    ports:
      - '{{portNumber}}:8080'
    networks:
      - network
    environment:
      - REDIS_HOST=redis
  redis:
    container_name: redis
    image: 'redis'
    ports:
      - '6379:6379'
    networks:
      - network
networks:
  network:
      driver: bridge