version: '3'
services:
  {{serverName}}:
    container_name: {{serverName}}
    image: $ApiImageTag 
    ports:
      - '{{portNumber}}:8080'
    networks:
      - {{serverName}}-network
    environment:
      - API_PORT=8080
networks:
  {{serverName}}-network:
      driver: bridge