version: '3'
services:
  {{serverName}}:
    container_name: {{serverName}}
    image: $ApiImageTag 
    ports:
      - '{{portNumber}}:8080'
    networks:
      - larry-network
    environment:
     
networks:
  larry-network:
      driver: bridge