version: '3'
services:
  dev-{{appName}}:
    container_name: dev-{{appName}}
    build:
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - ./../../../:/usr/src/app
      - ./../../../../{{authGithubProjectName}}/dist/{{authGithubProjectName}}:/usr/src/app/node_modules/{{authProjectName}}
    ports:
      - 4200:4200