version: '3'
services:
  api:
    container_name: dev-{{serverName}}
    build:
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - ./../../../:/usr/src/app
    ports:
      - '{{portNumber}}:8080'